
stages:
  - publish

variables:
  NUGET_REGISTRY_URL: "https://umane.emeal.nttdata.com/git/api/v4/projects/34206/packages/nuget/index.json"
  REGISTRY_SOURCE: "acrcloudliquid.azurecr.io"
  DOCKER_IMAGE: "$REGISTRY_SOURCE/cloudliquid"
  AZURE_CONTAINER_REGISTRY_USERNAME: "$ACR_USERNAME"
  AZURE_CONTAINER_REGISTRY_PASSWORD: "$ACR_PASSWORD"
  DOCKER_DRIVER: overlay2

#cache:
#  paths:
#    - .nuget/packages/


publish:
  stage: publish
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: dockerhost
  variables:
    DOCKER_HOST: tcp://dockerhost:2375/
#    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "docker registry login"
    - echo "$AZURE_CONTAINER_REGISTRY_PASSWORD" | docker login $REGISTRY_SOURCE --username $AZURE_CONTAINER_REGISTRY_USERNAME --password-stdin
    - echo "pushing image to registry"
    - ls -la
    - docker push $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_PIPELINE_ID
    - echo "image successfully pushed to registry"
  when: manual
  needs:
    - job: docker_build
      artifacts: true
  only:
    - main